[pytest]
minversion = 8.0
addopts = -ra -q --screenshot=on --video=retain-on-failure --tracing=retain-on-failure --html=reports/report.html --self-contained-html -W ignore::urllib3.exceptions.NotOpenSSLWarning
testpaths = tests
python_files = test_*.py
markers =
    api: REST and GraphQL API tests
    web: Web UI tests
    security: Security-focused cases
    a11y: Accessibility tests (ARIA, keyboard nav, labels)
filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
