[pytest]
minversion = 8.0
addopts = -ra -q --screenshot=on --video=retain-on-failure --tracing=retain-on-failure --html=reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
markers =
    api: REST and GraphQL API tests
    web: Web UI tests
    mobile: Mobile UI tests
