custom_fields:
- name: owner
  type: text
- name: jira_ticket
  type: text
generation_categories:
  accessibility: false
  edge: true
  functional: true
  negative: true
  security: true
labels:
- color: emerald
  name: sanity
- color: indigo
  name: regression
- color: amber
  name: smoke
- color: red
  name: critical
priorities:
- color: red
  name: P0
- color: orange
  name: P1
- color: amber
  name: P2
- color: slate
  name: P3
test_type_distribution:
  regression: 70
  sanity: 30
users:
- admin: true
  email: mayuresh49@gmail.com
  name: Mayuresh Kulkarni
  password_hash: $2b$12$zv9wirVO6oxerfYCzfPhGe30TeZMPt2RkrpMDx9U990beq.5y/TNq
  products: []
