LOCATOR_HEAL_TIMEOUT_MS = 2000
DEFAULT_BROWSER_TIMEOUT_MS = 10000
MISTRAL_CLOUD_TIMEOUT_S = 120
MISTRAL_LOCAL_TIMEOUT_S = 300

# Three-tier resilience
BROWSER_USE_MODEL = "qwen2.5:7b"
BROWSER_USE_OLLAMA_URL = "http://localhost:11434"
SKYVERN_BASE_URL = "http://localhost:8000"
SKYVERN_POLL_INTERVAL_S = 5
SKYVERN_MAX_WAIT_S = 120
